# Generated by Django 3.1 on 2023-03-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_photo', models.ImageField(upload_to='')),
                ('camera_name', models.CharField(max_length=30)),
                ('camera_desc', models.TextField()),
                ('camera_price', models.IntegerField()),
            ],
        ),
    ]
