# Generated by Django 3.1 on 2023-03-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcamera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcamera',
            name='camera_photo',
            field=models.ImageField(upload_to='site_media'),
        ),
    ]
