# Generated by Django 3.2.10 on 2023-03-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcamera', '0003_alter_addcamera_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcamera',
            name='camera_photo',
            field=models.FileField(upload_to='media'),
        ),
    ]
