# Generated by Django 3.2.10 on 2023-03-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcamera', '0006_alter_feedback_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='ContactUs',
        ),
    ]
